### ISSUE TITLE
To Dos

### ISSUE THREAD

**Issue by mblue9** [stemangiola/bioc2021_tidytranscriptomics#10]
To dos for workshop ping @stemangiola 

- Need Docker image by this Friday May 28th - have turned on build
- Update version to 1 beyond monash one?
- Incorporate any relevant changes from rladies and monash repos
- Need to add some interactive exercises/activities (polls?), requirement for long workshop, see below. For bulk could use some of the polls from ABACBS? For single cell maybe could include something showcasing the 3D plotly a bit more as people seem to like that? Or adapt something from the tidyseurat paper?

>We kindly remind you that long workshops are expected to be interactive. In other words, participants will be expected to have the time and opportunity to follow along and perform analysis themselves (https://bioc2021.bioconductor.org/submissions/).  

>As such, we encourage you to include multiple interactive segments throughout the workshop, making sure that participants have enough time to work through those interactive elements.

>For inspiration, we encourage you to have look at workshops from past conferences and decide what works best for you. Two examples of workshops that contain a high number of interactive elements are:

>https://isee.github.io/iSEEWorkshopEuroBioc2020/articles/recipes.html
>https://aedin.github.io/PCAworkshop/articles/d_sc_example.html_

**Comment by stemangiola** [comment]
> * Need Docker image by this Friday May 28th - have turned on build

Thanks!



> * Update version to 1 beyond monash one?

I would say, let's keep with 0.x.y until the whole thing will be more established and less changing



> * Incorporate any relevant changes from rladies and monash repos

I will create a branch and update, so you will be able to accept or reject the changes

**Comment by mblue9** [comment]
> Update version to 1 beyond monash one?
I would say, let's keep with 0.x.y until the whole thing will be more established and less changing

Ah sorry I wasn't clear, I meant did we want to add 1 (0.0.1) to the Monash ie. Monash was 0.8.1 so this one is version 0.8.2?

>Incorporate any relevant changes from rladies and monash repos
I will create a branch and update, so you will be able to accept or reject the changes

I've added a few comments, see what you think.

**Comment by stemangiola** [comment]
> Ah sorry I wasn't clear, I meant did we want to add 1 (0.0.1) to the Monash ie. Monash was 0.8.1 so this one is version 0.8.2?

Happy with that. Maybe in x.y.z, we can consider y as the addition of material and z as fixed/improvements (?)

**Comment by mblue9** [comment]
>Happy with that. Maybe in x.y.z, we can consider y as the addition of material and z as fixed/improvements (?)

Or do you think y should be new workshop/repo and z is fixed/improvements? To make it easier to keep track of what constitutes an increase in y? 
So we make this 0.9.0?
Or we use 0.8.2, I'm not fussed.

**Comment by stemangiola** [comment]
> > Happy with that. Maybe in x.y.z, we can consider y as the addition of material and z as fixed/improvements (?)
> 
> Or do you think y should be new workshop/repo and z is fixed/improvements? To make it easier to keep track of what constitutes an increase in y?
> So we make this 0.9.0?
> Or we use 0.8.2, I'm not fussed.

Yes true, let's make y a new workshop.
