### ISSUE TITLE
Add interactivity

### ISSUE THREAD

**Issue by mblue9** [stemangiola/bioc2021_tidytranscriptomics#14]
- Need to add some interactive exercises/activities (polls?), requirement for long workshop, see below. For bulk could use some of the polls from ABACBS? For single cell maybe could include something showcasing the 3D plotly a bit more as people seem to like that? Or adapt something from the tidyseurat paper?

>We kindly remind you that long workshops are expected to be interactive. In other words, participants will be expected to have the time and opportunity to follow along and perform analysis themselves (https://bioc2021.bioconductor.org/submissions/).  

>As such, we encourage you to include multiple interactive segments throughout the workshop, making sure that participants have enough time to work through those interactive elements.

>For inspiration, we encourage you to have look at workshops from past conferences and decide what works best for you. Two examples of workshops that contain a high number of interactive elements are:

>https://isee.github.io/iSEEWorkshopEuroBioc2020/articles/recipes.html
>https://aedin.github.io/PCAworkshop/articles/d_sc_example.html_

**Comment by stemangiola** [comment]
Another point of interactivity could be using
- plotly with volcano plot, to show how easy it is to make it interactive, and  
- interactive heatmap with interactiveComplexheatmap, which works with tidyHeatmap (`%>% ht_shiny()`)

**Comment by mblue9** [comment]
>Another point of interactivity could be using

>plotly with volcano plot, to show how easy it is to make it interactive, and
interactive heatmap with interactiveComplexheatmap, which works with tidyHeatmap (%>% ht_shiny())

By interactivity they mean participants interacting with the workshop e.g. doing exercises/activities as opposed to us showing code that's interactive. But if we could make those things into exercises that could be good - interactive code + interactive exercises = double interactivity :) Or is that what you meant?

**Comment by stemangiola** [comment]
No, I meant the other interactive. But still can be a good point for users to touch the mouse and scroll it on the plot.

I will think about exercises for single-cell

**Comment by mblue9** [comment]
>No, I meant the other interactive. But still can be a good point for users to touch the mouse and scroll it on the plot.

True.

>I will think about exercises for single-cell

Great!

**Comment by stemangiola** [comment]
About the pools, a possibility, I'm not sure if its candy nature is compatible with us 

https://www.menti.com/

**Comment by mblue9** [comment]
>About the pools, a possibility, I'm not sure if its candy nature is compatible with us

>https://www.menti.com/

I started having a look at that. We're allowed 2 questions and 5 quiz questions on the free plan which may be ok. I might try it out when I get a chance.

**Comment by mblue9** [comment]
Have created a quiz for the polls here https://www.menti.com/iizqjvpqww need to add multiple choice options for the single-cell answers.

**Comment by mblue9** [comment]
Notes on mentimeter

Running quiz
- People need to go to the link and create a name for their avatar
- Then we need to have the slide open that they're viewing e.g Slide 1 with quiz question (we control what they see(
- Use right arrow to go to next slide

Setting up quiz
- We're allowed a max of 5 quiz slides so if we want to add other questions we need to change the ones we've got
- To add quiz question Add slide of Type Quiz, write in questions and answers and tick the correct answer
- We can set countdown times for each slide under Content default is 15secs, I set the quiz question 1 to 120secs we can give shorter/longer
- Access code expires after 2 days
- Mentimeter does seem best to use for large online workshop as [few others](https://jobwherever.com/best-6-online-quiz-makers-3-free-and-3-paid/) Ahaslides and Kahoot only allow ~10 people without paid plan
