### ISSUE TITLE
add describe_transcripts

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/bioc2021_tidytranscriptomics#23]
Hello @mblue9, I think a nice quick-to-explain feature of tidybulk is

```r
describe_transcript()
```

where for human (and mouse?) you can add a descriptive column for the genes, so to make the interpretation much quicker less frustrating.

What do you think?

**Comment by stemangiola** [comment]
It's also true that this is not a tidybulk workshop

**Comment by mblue9** [comment]
I'm not sure about adding that as we show how to get symbols using Annotation DBI org package and could probably adapt that command to also get the description. Might be confusing to introduce a separate method.
