### ISSUE TITLE
Activate GitHub pages site

### ISSUE THREAD

**Issue by mblue9** [stemangiola/bioc2021_tidytranscriptomics#3]
Just noting to do - need to activate the website https://stemangiola.github.io/bioc2021_tidytranscriptomics/articles/tidytranscriptomics.html

**Comment by stemangiola** [comment]
I don't see the website branch though :(

**Comment by mblue9** [comment]
I think we need the actions here to pass at least once, at the moment they're errorring before they get to the website build. I've just commented out the code with the latest error in the supplementary and will see if I can get this to pass today.

**Comment by mblue9** [comment]
Branch is there now https://github.com/stemangiola/bioc2021_tidytranscriptomics/tree/gh-pages

**Comment by stemangiola** [comment]
Yee! Thanks! Done.

**Comment by mblue9** [comment]
Great 👍
