### ISSUE TITLE
Minor bugs?

### ISSUE THREAD

**Issue by aghatpande** [stemangiola/bioc2021_tidytranscriptomics#35]
Hi, I noticed these two lines refer to "treated" samples and "SRR1039" which are from the "airway" data and not single cell? Should the text refer to "cell cycle phases" and switching to lower case?
I am still working my way through your excellent workshop and figuring out how best to use the flexibility that tidyverse brings. Hope to use this and tidyseurat to process a single cell RNA seq dataset I am analyzing for someone.

https://github.com/stemangiola/bioc2021_tidytranscriptomics/blob/21a5a143e6de187bfcb7f71c5090e1660bc30952/vignettes/tidytranscriptomics.Rmd#L775
https://github.com/stemangiola/bioc2021_tidytranscriptomics/blob/21a5a143e6de187bfcb7f71c5090e1660bc30952/vignettes/tidytranscriptomics.Rmd#L787

**Comment by stemangiola** [comment]
Thanks for reporting!
